/*
 * api de eventos
 * Api utilizada no projeto final de disciplina do curso de ADS no IFPI
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Buscar uma atividade .
     *
     * Retorna uma atividade baseado no id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void atividadeBuscarAtividadeIdGetTest() throws ApiException {
        String id = null;
        api.atividadeBuscarAtividadeIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Cadastrar Atividade
     *
     * Recebe uma response de atividade
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void atividadeCadastrarPostTest() throws ApiException {
        String nome = null;
        String termino = null;
        Integer valor = null;
        Integer tipoAtividade = null;
        Integer evento = null;
        api.atividadeCadastrarPost(nome, termino, valor, tipoAtividade, evento);

        // TODO: test validations
    }
    
    /**
     * Listar atividades
     *
     * Retorna uma lista de atividades.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void atividadeListarGetTest() throws ApiException {
        api.atividadeListarGet();

        // TODO: test validations
    }
    
    /**
     * Listar tipos de atividades
     *
     * Retorna uma lista dos tipos de atividades.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void atividadeListarTiposGetTest() throws ApiException {
        api.atividadeListarTiposGet();

        // TODO: test validations
    }
    
    /**
     * listar cupons
     *
     * Retorna uma lista de cupons.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cupomAplicarCodigoGetTest() throws ApiException {
        String codigo = null;
        api.cupomAplicarCodigoGet(codigo);

        // TODO: test validations
    }
    
    /**
     * Cadastrar um Cupom
     *
     * Recebe uma response de Cupom
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cupomCadastrarPostTest() throws ApiException {
        String descricao = null;
        Integer evento = null;
        Integer dataValidade = null;
        Boolean utilizado = null;
        api.cupomCadastrarPost(descricao, evento, dataValidade, utilizado);

        // TODO: test validations
    }
    
    /**
     * Obter cupons
     *
     * Retorna um cupom.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cupomIdCuponsGetTest() throws ApiException {
        String id = null;
        api.cupomIdCuponsGet(id);

        // TODO: test validations
    }
    
    /**
     * listar cupons
     *
     * Retorna uma lista de cupons.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cupomListarGetTest() throws ApiException {
        api.cupomListarGet();

        // TODO: test validations
    }
    
    /**
     * Cadastrar Evento
     *
     * Recebe uma response de evento
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void eventoCadastrarPostTest() throws ApiException {
        String descricao = null;
        String dataInicio = null;
        Integer dataTermino = null;
        Integer estadoEvento = null;
        Integer usuario = null;
        List<Integer> atividades = null;
        List<Integer> tags = null;
        List<Integer> colaboradores = null;
        List<Integer> cupons = null;
        api.eventoCadastrarPost(descricao, dataInicio, dataTermino, estadoEvento, usuario, atividades, tags, colaboradores, cupons);

        // TODO: test validations
    }
    
    /**
     * Cancelar evento.
     *
     * Cancelamento do evento relacionado ao id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void eventoCancelarIdGetTest() throws ApiException {
        String id = null;
        api.eventoCancelarIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Deletar evento.
     *
     * Deletar evento relacionado ao id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void eventoDeleteIdDeleteTest() throws ApiException {
        String id = null;
        api.eventoDeleteIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * listar eventos
     *
     * Retorna uma lista de usuário.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void eventoListarGetTest() throws ApiException {
        api.eventoListarGet();

        // TODO: test validations
    }
    
    /**
     * Mudar estado do evento.
     *
     * Muda o estado do evento relacionado ao id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void eventoMudarEstadoIdGetTest() throws ApiException {
        String id = null;
        api.eventoMudarEstadoIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Participar do evento.
     *
     * Participar do evento relacionado ao id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void eventoParticiparIdGetTest() throws ApiException {
        String id = null;
        api.eventoParticiparIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Cadastra Usuário
     *
     * Recebe uma response de usuário
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usuarioCadastrarPostTest() throws ApiException {
        String nome = null;
        String email = null;
        String password = null;
        Integer evento = null;
        api.usuarioCadastrarPost(nome, email, password, evento);

        // TODO: test validations
    }
    
    /**
     * Mostrar Usuário
     *
     * Retorna uma usuário baseado no email.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usuarioEmailGetTest() throws ApiException {
        String email = null;
        api.usuarioEmailGet(email);

        // TODO: test validations
    }
    
    /**
     * Retorna inscrições do usuario
     *
     * Retorna uma lista com as inscrições do usuario baseados no seu id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usuarioIdMinhasInscricoesGetTest() throws ApiException {
        String id = null;
        api.usuarioIdMinhasInscricoesGet(id);

        // TODO: test validations
    }
    
    /**
     * listar usuarios
     *
     * Retorna uma lista de usuário.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usuarioListarGetTest() throws ApiException {
        api.usuarioListarGet();

        // TODO: test validations
    }
    
    /**
     * Logar Usuário
     *
     * Recebe uma response de usuário
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usuarioLoginPostTest() throws ApiException {
        String email = null;
        String password = null;
        api.usuarioLoginPost(email, password);

        // TODO: test validations
    }
    
}
